apiVersion: v1
kind: Service
metadata:
  name: cd-example
  labels:
    app: cd-example
spec:
  type: NodePort
  selector:
    app: cd-example
  ports:
    - name: http
      port: 8080
      targetPort: 8080
