apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cd-example
  name: cd-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cd-example
  template:
    metadata:
      name: cd-example
      labels:
        app: cd-example
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: tasklist_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/tasklist_db
            - name: SPRING_DATASOURCE_USERNAME
              value: tasklist_user
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
          image: docker.io/local/devops-demo-cd:v1.0.0
          imagePullPolicy: Never
          name: cd-example
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
